# Generated by Django 3.1.7 on 2021-03-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='colour',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/user01.png', upload_to='blogs'),
        ),
    ]
