# Generated by Django 3.1.7 on 2021-03-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210330_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/user01.jpeg', upload_to='blogs'),
        ),
    ]
