# Generated by Django 3.1.7 on 2021-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210330_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='accounts/user01.jpeg', upload_to='blogs'),
        ),
    ]
