# Generated by Django 3.1.4 on 2021-03-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
    ]
