# Generated by Django 3.1.7 on 2021-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_oko'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sfae',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
