# Generated by Django 3.1.7 on 2021-03-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_sfae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sfae',
        ),
    ]
