# Generated by Django 3.1.7 on 2021-03-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='oko',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
