# Generated by Django 3.1.7 on 2021-03-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_oko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='oko',
        ),
    ]
