# Generated by Django 3.1.7 on 2021-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210407_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, default='9999999999', max_length=10),
        ),
    ]
