# Generated by Django 3.1.7 on 2021-02-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        #migrations.RenameModel('Books', 'Book')
    ]
