# Generated by Django 3.1.4 on 2021-03-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_uuidmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UUIDModel',
        ),
    ]
