# Generated by Django 3.1.7 on 2021-02-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210220_2114'),
    ]

    operations = [
        #migrations.RenameModel('Books', 'Book')
        
    ]
