# Generated by Django 3.1.7 on 2021-02-20 22:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210220_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='books')),
                ('stock', models.IntegerField()),
                ('availible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('num_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=240)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='shop.author')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('title',),
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.AlterField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(to='shop.Book'),
        ),
    ]
