# Generated by Django 3.1.7 on 2021-04-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='star_rating',
            field=models.FloatField(),
        ),
    ]
