# Generated by Django 3.1.3 on 2021-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210410_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
