# Generated by Django 3.1.3 on 2021-03-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vouchers',
            new_name='Voucher',
        ),
    ]
