# Generated by Django 3.1.7 on 2021-04-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20210326_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='anounce',
            field=models.BooleanField(default='False'),
        ),
    ]
