# Generated by Django 3.1.7 on 2021-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucher_anounce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='anounce',
            field=models.BooleanField(),
        ),
    ]
